"""
Keyword-matched exercise library. Maps recommendation text (generated by
movement_quality.py in Milestone 2) to concrete corrective exercises a
physiotherapist can assign. This is a lookup table, not a trained
recommender — it matches keywords ("knee", "hip", "trunk", etc.) that
already appear in the recommendation strings your pipeline produces.
"""

EXERCISE_LIBRARY = {
    "knee": [
        {"name": "Single-leg squat", "sets": "3", "reps": "10 per side", "target": "Knee stability"},
        {"name": "Step-downs", "sets": "3", "reps": "12 per side", "target": "Knee control on landing"},
        {"name": "Glute bridge", "sets": "3", "reps": "15", "target": "Glute activation to support knee"},
    ],
    "hip": [
        {"name": "Hip abductor raises", "sets": "3", "reps": "15 per side", "target": "Hip stability"},
        {"name": "Clamshells", "sets": "3", "reps": "15 per side", "target": "Hip external rotator strength"},
        {"name": "Lateral band walks", "sets": "3", "reps": "20 steps", "target": "Hip abductor endurance"},
    ],
    "elbow": [
        {"name": "Wrist flexor/extensor stretch", "sets": "3", "reps": "30 sec hold", "target": "Forearm mobility"},
        {"name": "Eccentric wrist curls", "sets": "3", "reps": "12", "target": "Elbow tendon loading"},
    ],
    "trunk": [
        {"name": "Dead bug", "sets": "3", "reps": "10 per side", "target": "Core control / trunk stability"},
        {"name": "Bird dog", "sets": "3", "reps": "10 per side", "target": "Trunk and hip coordination"},
    ],
    "asymmetry": [
        {"name": "Single-leg balance hold", "sets": "3", "reps": "30 sec per side", "target": "Bilateral symmetry"},
    ],
    "training load": [
        {"name": "Active recovery / mobility session", "sets": "1", "reps": "20 min", "target": "Overuse risk reduction"},
    ],
    "fatigue": [
        {"name": "Sleep & recovery review", "sets": "-", "reps": "-", "target": "Fatigue management (non-exercise)"},
    ],
}

GENERIC_FALLBACK = [
    {"name": "General mobility flow", "sets": "1", "reps": "10 min", "target": "General movement quality"},
]


def suggest_exercises(recommendations: list[str]) -> list[dict]:
    """
    Scans recommendation strings for keywords and returns matched exercises.
    Deduplicates by exercise name. Falls back to a generic recommendation
    if nothing matches.
    """
    matched = []
    seen_names = set()

    for rec in recommendations:
        rec_lower = rec.lower()
        for keyword, exercises in EXERCISE_LIBRARY.items():
            if keyword in rec_lower:
                for ex in exercises:
                    if ex["name"] not in seen_names:
                        matched.append({**ex, "matched_from": rec})
                        seen_names.add(ex["name"])

    if not matched:
        matched = [{**ex, "matched_from": "General recommendation"} for ex in GENERIC_FALLBACK]

    return matched